---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
    spec:
      containers:
        - name: controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.9.1 # Hoặc phiên bản bạn dùng
          args:
            - /nginx-ingress-controller
            - --enable-ssl-passthrough
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
            - --ingress-class=nginx
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 5044
              name: logstash-beats
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        # Các cấu hình khác như nodeSelector, tolerations tuỳ hạ tầng

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "5044": "default/logstash-beats:5044"

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
spec:
  type: LoadBalancer # hoặc NodePort tuỳ bạn
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: logstash-beats
      port: 5044
      targetPort: 5044
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx

---
apiVersion: v1
kind: Service
metadata:
  name: logstash-beats
  namespace: default
spec:
  ports:
    - port: 5044
      targetPort: 5044
      protocol: TCP
      name: beats
  selector:
    app: logstash

# filebeat.yml
# output.logstash:
#   hosts: ["<INGRESS_LOADBALANCER_IP>:5044"]
#   ssl.enabled: true                # Bật nếu Logstash sử dụng SSL
#   ssl.certificate_authorities: ["/path/to/ca.crt"]  # Nếu có CA
